### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by jimbok8** [jeo/jeo#90]
In package io.jeo.filter.cql the following files are missing:

ParseException
ECQLParser
FilterCompilationUnit

**Comment by jdeolive** [comment]
Hi. These classes are generated during the build process. If you build with maven they should be generated automatically. In some IDE's you may need to explicitly have them generated (I know i have to do this occasionally with IntelliJ).

If you can give me more info about your setup I can hopefully better assist.
