### ISSUE TITLE
mvn install

### ISSUE THREAD

**Issue by jimbok8** [jeo/jeo#93]
I have downloaded the jeo-master zip file. Having installed maven I have run this command:
mvn install

this produces the following error, which I also get having loaded jeo-master into Netbeans, and issued a build command.
Please could you help suggest what I am doing wrong?
Thanks.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class Files
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] jeo ................................................ SUCCESS [  4.434 s]
[INFO] Core ............................................... FAILURE [  8.876 s]

**Comment by jdeolive** [comment]
Hmmm... my gut tells me java isn't configured properly. Is there any more build output to look at?
I vaguely remember running into something similar before that involved having a jre but not a jdk, so no compiler tools, etc... I don't use netbeans so I can't really help much there on how to check that.

Are you able to build with maven from the command line?

**Comment by jimbok8** [comment]
Thanks for the prompt reply.
It also fails from the command line using mvn install.
I suspect it is because I am using a non-standard location for the JDK; however, I have explicitly set JAVA_HOME and M2_HOME and added both of these to the PATH.

I have just managed to get the command "mvn install" to finish by modifying pom.xml by by adding <skip>true</skip> to the surefire plugin section, see below.

     <plugin>
       <artifactId>maven-surefire-plugin</artifactId>
       <version>2.15</version>
       <configuration>
         <argLine>-Djava.library.path=${java.library.path}</argLine>         
         <skip>true</skip>         
       </configuration>
     </plugin>

**Comment by jdeolive** [comment]
I see. Could you provide the output of ``mvn -version``?

**Comment by jimbok8** [comment]
C:\Users\kayji\Downloads\Programs\apache-maven-3.3.3>mvn -version
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:3
7+01:00)
Maven home: C:\Users\kayji\Downloads\Programs\apache-maven-3.3.3
Java version: 1.8.0_45, vendor: Sun Microsystems Inc.
Java home: C:\Users\kayji\Downloads\Programs\JAVA\jdk-8u45-windows-x64\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by jdeolive** [comment]
Thanks for the info. Luckily I was able to reproduce the issue and I believe it has to do with the java.library.path reference not being quoted and hence not dealing with spaces in the path. Fixing momentarily.
