### ISSUE TITLE
v0.7 repo question

### ISSUE THREAD

**Issue by rgaskill** [jeo/jeo#96]
The latest version of jeo I see in maven central is [v0.6](http://search.maven.org/#search%7Cga%7C1%7Cjeo) is v0.7 available in a different maven repo?

**Comment by jdeolive** [comment]
It looks like the 0.7 version never got pushed to maven central. I'll start that process now and update this ticket when it's available. If you're ok with using snapshots you can pull from this repo:

    https://oss.sonatype.org/content/repositories/snapshots

**Comment by rgaskill** [comment]
Awesome Thanks!

**Comment by jdeolive** [comment]
No problem! I've pushed the release but it usually takes maven central a few hours to update. In the meantime you can pull from the staging repository if you like:

    https://oss.sonatype.org/content/repositories/staging/io/jeo/jeo/0.7/

**Comment by rgaskill** [comment]
Thanks Again!
