### ISSUE TITLE
problem on Feature.put(Geometry g)

### ISSUE THREAD

**Issue by wsw0108** [jeo/jeo#97]
``` java
Feature f = new MapFeature("id");
Geometry g;
f.put(g);
```

Under this case, `g` will not be put to the map anyway.

**Comment by jdeolive** [comment]
Thanks for the report. Indeed you are correct. Looks like MapFeature.put only supports updating a geometry if one already exists. Workaround is to explicitly specify a field name:

    f.put("geometry", g);

We should fix this but I am not sure the best way. Options include:

- throwing an exception, this is what ListFeature does when you call put(Geometry) when there is no schema, and no existing geometries in the list
- just using a field name like "geometry" by default
- use the null key in the map
...
